version: "3.8"
services:
  couchbase:
    build:
      context: "test/couchbase"
    ports:
      - "8091:8091"
      - "11210:11210"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user:password@localhost:8091/pools/default/buckets/dcp-test" ]
      interval: 2s
      timeout: 3s
      retries: 60
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.6.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  kowl:
    image: quay.io/cloudhut/kowl:master-59f68da
    container_name: kowl
    depends_on:
      - broker
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: 'broker:29092'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/topics/topicname/partitions || exit 1
      interval: 2s
      timeout: 3s
      retries: 60
  redpanda-topic-create:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.8
    container_name: redpanda-topic-create
    depends_on:
      - kowl
    entrypoint: [ "bash", "-c", "sleep 10 && rpk topic create topicname -c max.message.bytes=10485760 --brokers broker:29092" ]