{
 "title": "Go DCP Kafka Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DCP Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "cbgo_dcp_latency_ms_current", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Kafka Batch Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cbgo_kafka_connector_batch_produce_latency_ms_current",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mutation Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_mutation_total) by (app)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_process_latency_ms_current) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Expiration Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_expiration_total) by (app)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DCP Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cbgo_lag_current) by (app)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Member Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_total_members_current) by(pod)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Deletion Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_deletion_total) by (app)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connector Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_kafka_connector_latency_ms_current) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rebalance Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbgo_rebalance_current", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "GO Memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{pod}} - bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{pod}} - stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{pod}} - heap inuse" }
   ]
  },
  {
   "title": "Offset Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cbgo_offset_write_latency_ms_current) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{pod}} - resident" }
   ]
  },
  {
   "title": "Open FDS Deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[$__range])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes[$__range])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{pod}}: {{quantile}}" }
   ]
  },
  {
   "title": "GO Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes[$__range])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$__range])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes[$__range])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes[$__range])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  }
 ]
}